import { Platform } from "react-native";
import * as FileSystem from "expo-file-system";
import * as Print from "expo-print";

export interface PDFData {
  customerName: string;
  phoneNumber: string;
  aadhaarNumber: string;
  imei: string;
  phoneImageUri: string | null;
  timestamp: string;
}

function esc(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

async function uriToBase64(uri: string): Promise<string | null> {
  try {
    if (Platform.OS === "web") {
      // On web, uri is already a blob: or data: URL — convert via fetch
      const response = await fetch(uri);
      const blob = await response.blob();
      return await new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onloadend = () => {
          const result = reader.result as string;
          // strip the "data:...;base64," prefix
          resolve(result.split(",")[1] ?? null);
        };
        reader.onerror = reject;
        reader.readAsDataURL(blob);
      });
    }
    return await FileSystem.readAsStringAsync(uri, {
      encoding: FileSystem.EncodingType.Base64,
    });
  } catch {
    return null;
  }
}

export async function generateReceiptPDF(data: PDFData): Promise<string> {
  let imageTag = "";
  if (data.phoneImageUri) {
    const b64 = await uriToBase64(data.phoneImageUri);
    if (b64) {
      imageTag = `<div class="img-wrap">
        <p class="label">Device Photo</p>
        <img src="data:image/jpeg;base64,${b64}" class="phone-img" />
      </div>`;
    }
  }

  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<style>
* { box-sizing: border-box; margin: 0; padding: 0; }
body {
  font-family: -apple-system, Helvetica Neue, Arial, sans-serif;
  background: #ffffff;
  color: #111928;
  padding: 0;
}
.header {
  background: #1B4FFF;
  color: #fff;
  padding: 28px 32px 24px;
}
.header-title { font-size: 26px; font-weight: 700; letter-spacing: -0.3px; }
.header-sub { font-size: 12px; opacity: 0.75; margin-top: 2px; }
.badge {
  display: inline-block;
  background: rgba(255,255,255,0.18);
  border-radius: 20px;
  padding: 3px 12px;
  font-size: 11px;
  margin-top: 10px;
}
.body { padding: 24px 32px; }
.row { margin-bottom: 14px; }
.label {
  font-size: 10px;
  text-transform: uppercase;
  letter-spacing: 0.7px;
  color: #6B7280;
  font-weight: 700;
  margin-bottom: 3px;
}
.value {
  font-size: 15px;
  font-weight: 600;
  color: #111928;
  background: #F3F5F9;
  padding: 10px 14px;
  border-radius: 8px;
}
.divider { height: 1px; background: #E5E7EB; margin: 20px 0; }
.img-wrap { margin-top: 16px; }
.phone-img {
  display: block;
  max-width: 180px;
  max-height: 180px;
  border-radius: 10px;
  margin-top: 8px;
  border: 2px solid #E5E7EB;
  object-fit: cover;
}
.footer {
  margin-top: 28px;
  text-align: center;
  font-size: 10px;
  color: #9CA3AF;
  border-top: 1px solid #E5E7EB;
  padding-top: 16px;
}
</style>
</head>
<body>
<div class="header">
  <div class="header-title">DealerFlow</div>
  <div class="header-sub">Purchase Receipt</div>
  <span class="badge">Used Mobile Device Record</span>
</div>
<div class="body">
  <div class="row">
    <div class="label">Customer Name</div>
    <div class="value">${esc(data.customerName)}</div>
  </div>
  <div class="row">
    <div class="label">Phone Number</div>
    <div class="value">${esc(data.phoneNumber)}</div>
  </div>
  <div class="row">
    <div class="label">Aadhaar Number</div>
    <div class="value">${esc(data.aadhaarNumber || "Not provided")}</div>
  </div>
  <div class="row">
    <div class="label">IMEI Number</div>
    <div class="value">${esc(data.imei)}</div>
  </div>
  <div class="row">
    <div class="label">Date &amp; Time</div>
    <div class="value">${esc(data.timestamp)}</div>
  </div>
  ${imageTag}
  <div class="footer">
    <p>Generated by DealerFlow &bull; ${new Date().getFullYear()}</p>
    <p style="margin-top:4px">This document serves as a record of used mobile device purchase.</p>
  </div>
</div>
</body>
</html>`;

  const { uri } = await Print.printToFileAsync({ html, base64: false });
  return uri;
}
